<?php

use Drupal\Core\File\FileExists;

/**
 * @file
 * Install, update and uninstall functions for the cwd test module.
 */

/**
 * Implements hook_install().
 */
function cwd_saml_mapping_install() {
  $override_config = [
    'saml_sp.settings',
    'saml_sp_drupal_login.config',
    'cwd_saml_mapping.config_form',
  ];

  $is_command_line = (php_sapi_name() === 'cli');
  if (!$is_command_line) {
    \Drupal::messenger()->addWarning('When installing this module from the web interface, you will need to manually configure your entity id and assertion urls.');
  }
  else {
    $confirmed = 'n';
    // do until confirmed is y
    while ($confirmed != 'y') {
      fwrite(STDOUT, "Enter the panteon machine name for your SAML configuration: ");
      $input = trim(fgets(STDIN));
      fwrite(STDOUT, "Enter the email of the responsible party for your SAML configuration: ");
      $email = trim(fgets(STDIN));
      fwrite(STDOUT, "Enter the domain name for your SAML configuration: ");
      $domain = trim(fgets(STDIN));
      fwrite(STDOUT, "You entered pantheon machine name: " . $input . "\n");
      fwrite(STDOUT, "You entered email: " . $email . "\n");
      fwrite(STDOUT, "You entered domain name: " . $domain . "\n");
      fwrite(STDOUT, "Is this correct? (y/n): ");
      $confirmed = trim(fgets(STDIN));
    }
  }

  if (empty($input)) {
    $input = "*";
  }

  foreach ($override_config as $config) {
    // Get your custom config
    $cfg = \Drupal::configFactory()->getEditable('override.' . $config);
    // Get Config object
    if ($config == 'saml_sp.settings' && $is_command_line) {
      $current = $cfg->get('assertion_urls');
      $current = str_replace('*', $input, $current);
      $cfg->set('assertion_urls', $current);
      $entity_id = $cfg->get('entity_id');
      $entity_id = str_replace('*', $input, $entity_id);
      $cfg->set('entity_id', $entity_id);
    }
    $settings = \Drupal::configFactory()->getEditable($config);
    // Override all data that can be overridden
    $settings->setData($cfg->get())->save();
    // Get rid of your custom config
    $cfg->delete();
  }

  if (empty($email)) {
    $email = "admin@cornell.edu";
  }
  if (empty($domain)) {
    $domain = "cornell.edu";
  }

  if ($is_command_line) {
    _generate_ssl_certificates_with_php($email, $domain);
    _output_instructions_cli();
  }
  else {
    _output_instructions_web();
  }

  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_uninstall().
 */
function cwd_saml_mapping_uninstall() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Update all saml_role_mapping entities to have new samlother and specialmatchcriteria values.
 */
function cwd_saml_mapping_update_91001() {
  $entity_ids = \Drupal::entityQuery('saml_role_mapping')->execute();
  $configs = \Drupal::entityTypeManager()->getStorage('saml_role_mapping')->loadMultiple($entity_ids);
  foreach ($configs as $config) {
    $config->set('samlother', 'n/a');
    $config->set('specialmatchcriteria', 'none');
    $config->save();
  }
}

/**
 * Register entities saml_login_redirect and saml_logout_redirect.
 */
function cwd_saml_mapping_update_91002() {
  $entity_type_definition = \Drupal::service('entity_type.manager')->getDefinition('saml_login_redirect');
  \Drupal::entityDefinitionUpdateManager()->installEntityType($entity_type_definition);
  $entity_type_definition = \Drupal::service('entity_type.manager')->getDefinition('saml_logout_redirect');
  \Drupal::entityDefinitionUpdateManager()->installEntityType($entity_type_definition);
}




function _output_instructions_cli() {
  $instructions = [
    "YOU MUST SYNC YOUR CERTS TO ALL PANTHEON ENVIRONMENTS!!!!!\n\n",
    "To sync your private files to Pantheon, you can use the following command from sites/default:\n",
    "- rsync -rLvz --size-only --ipv4 --ignore-existing --progress -e 'ssh -p 2222' files/private/ --temp-dir=~/tmp/ COPY_THE_USERNAME_AND_SERVER_CONNECITON_INFO_FROM_PANTHEON_UNDER_COMMANDLINE_SFTP:files/private/\n\n",
  ];
  foreach ($instructions as $instruction) {
    fwrite(STDOUT, $instruction);
  }
}

function _output_instructions_web() {
  $instructions = [
    "Create the certificate directory if it does not already exist:\n",
    "- Run at doc root of repo\n",
    "- mkdir -p web/sites/default/files/private/simplesaml/cert\n\n",
    "After installation, be sure to regenerate your SSL certificates with the following command:\n",
    "- openssl req -newkey rsa:3072 -new -x509 -days 3652 -nodes -out web/sites/default/files/private/simplesaml/cert/saml.crt -keyout web/sites/default/files/private/simplesaml/cert/saml.pem;\n\n",
    "The paths for the certs which should be automatically configured for you:\n",
    "- private://simplesaml/cert/saml.crt\n",
    "- private://simplesaml/cert/saml.pem\n\n",
    "YOU MUST SYNC YOUR CERTS TO ALL PANTHEON ENVIRONMENTS!!!!!\n\n",
    "To sync your private files to Pantheon, you can use the following command from sites/default:\n",
    "- rsync -rLvz --size-only --ipv4 --ignore-existing --progress -e 'ssh -p 2222' files/private/ --temp-dir=~/tmp/ COPY_THE_USERNAME_AND_SERVER_CONNECITON_INFO_FROM_PANTHEON_UNDER_COMMANDLINE_SFTP:files/private/\n\n",
  ];
  foreach ($instructions as $instruction) {
    \Drupal::messenger()->addStatus($instruction);
  }
}

function _generate_ssl_certificates_with_php($email = "admin@cornell.edu", $domain = "cornell.edu") {
  $config = [
    "digest_alg" => "sha256",
    "private_key_bits" => 3072,
    "private_key_type" => OPENSSL_KEYTYPE_RSA,
  ];

  $dn = [
    "countryName" => "US",
    "stateOrProvinceName" => "New York",
    "localityName" => "Ithaca",
    "organizationName" => "Cornell University",
    "organizationalUnitName" => "Cornell University",
    "commonName" => $domain,
    "emailAddress" => $email,
  ];

  // Create the private and public key
  $res = openssl_pkey_new($config);
  // Generate a certificate signing request
  $csr = openssl_csr_new($dn, $res, $config);

  // Self-sign the certificate
  $x509 = openssl_csr_sign($csr, NULL, $res, 3652, $config);

  openssl_x509_export($x509, $certout);
  openssl_pkey_export($res, $pkeyout);

  // drupal put file in private://simplesaml2/cert/ using FileStorage
  $file_system = \Drupal::service('file_system');
  // create directory if it does not exist
  $directory = 'private://simplesaml/cert/';
  if (!file_exists($file_system->realpath($directory))) {
    $file_system->mkdir($directory, 0700, TRUE);
  }
  // drupal save file to directory do not use file_save_data.
  $cert_file = $file_system->saveData($certout, $directory . 'saml.crt', FileExists::Replace);
  $key_file = $file_system->saveData($pkeyout, $directory . 'saml.pem', FileExists::Replace);

  if (php_sapi_name() === 'cli') {
    fwrite(STDOUT, "Generated SSL certificates at:\n");
    fwrite(STDOUT, "- " . $directory . 'saml.crt' . "\n");
    fwrite(STDOUT, "- " . $directory . 'saml.pem' . "\n");
  }
  else {
    \Drupal::messenger()->addStatus("Generated SSL certificates at:\n");
    \Drupal::messenger()->addStatus("- " . $directory . 'saml.crt' . "\n");
    \Drupal::messenger()->addStatus("- " . $directory . 'saml.pem' . "\n");
  }
}
