cwd_saml_mapping.saml_role_mapping.*:
  type: config_entity
  label: SAML Role Mapping
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    role:
      type: string
    samlprop:
      type: string
    samlother:
      type: string
    values:
      type: string
    specialmatchcriteria:
      type: string

block.settings.cwd_saml_mapping_single_sign_on_login_block:
  type: block_settings
  label: 'Single Sign-On Login Block block'
  mapping:
    block_text:
      type: string
      label: Block Text
